/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package kin.ecosystem.core.network.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * an error
 */
public class Error {
    @SerializedName("error")
    private String error = null;
    @SerializedName("message")
    private String message = null;
    @SerializedName("code")
    private Integer code = null;

    public Error(String error, String message, Integer code) {
        this.error = error;
        this.message = message;
        this.code = code;
    }

    public Error error(String error) {
        this.error = error;
        return this;
    }


    /**
     * Get error
     *
     * @return error
     **/
    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public Error message(String message) {
        this.message = message;
        return this;
    }


    /**
     * Get message
     *
     * @return message
     **/
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Error code(Integer code) {
        this.code = code;
        return this;
    }


    /**
     * Get code
     *
     * @return code
     **/
    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Error error = (Error) o;
        return Objects.equals(this.error, error.error) &&
                Objects.equals(this.message, error.message) &&
                Objects.equals(this.code, error.code);
    }

    @Override
    public int hashCode() {
        return Objects.hash(error, message, code);
    }
}



