/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kin.ecosystem.core.network.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

/**
 * IncomingTransferRequest
 */

public class IncomingTransferRequest {

	@SerializedName("title")
	private String title = null;

	@SerializedName("description")
	private String description = null;

	@SerializedName("memo")
	private String memo = null;

	@SerializedName("wallet_address")
	private String walletAddress = null;

	@SerializedName("app_id")
	private String appId = null;

	public IncomingTransferRequest title(String title) {
		this.title = title;
		return this;
	}

	/**
	 * Get title
	 *
	 * @return title
	 **/
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public IncomingTransferRequest description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * Get description
	 *
	 * @return description
	 **/
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public IncomingTransferRequest memo(String memo) {
		this.memo = memo;
		return this;
	}

	/**
	 * blockchain transaction memo - goes into the blockchain_data
	 *
	 * @return memo
	 **/
	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public IncomingTransferRequest walletAddress(String walletAddress) {
		this.walletAddress = walletAddress;
		return this;
	}

	/**
	 * address which payment will arrive from
	 *
	 * @return walletAddress
	 **/
	public String getWalletAddress() {
		return walletAddress;
	}

	public void setWalletAddress(String walletAddress) {
		this.walletAddress = walletAddress;
	}

	public IncomingTransferRequest appId(String appId) {
		this.appId = appId;
		return this;
	}

	/**
	 * the app id of the sender
	 *
	 * @return appId
	 **/
	public String getAppId() {
		return appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		IncomingTransferRequest incomingTransferRequest = (IncomingTransferRequest) o;
		return Objects.equals(this.title, incomingTransferRequest.title) &&
			Objects.equals(this.description, incomingTransferRequest.description) &&
			Objects.equals(this.memo, incomingTransferRequest.memo) &&
			Objects.equals(this.walletAddress, incomingTransferRequest.walletAddress) &&
			Objects.equals(this.appId, incomingTransferRequest.appId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(title, description, memo, walletAddress, appId);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class IncomingTransferRequest {\n");

		sb.append("    title: ").append(toIndentedString(title)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
		sb.append("    walletAddress: ").append(toIndentedString(walletAddress)).append("\n");
		sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
