/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kin.ecosystem.core.network.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

/**
 * OutgoingTransfer
 */
public class OutgoingTransfer {

	@SerializedName("wallet_address")
	private String walletAddress = null;

	@SerializedName("app_id")
	private String appId = null;

	@SerializedName("title")
	private String title = null;

	@SerializedName("description")
	private String description = null;

	@SerializedName("memo")
	private String memo = null;

	@SerializedName("amount")
	private Integer amount = null;

	public OutgoingTransfer walletAddress(String walletAddress) {
		this.walletAddress = walletAddress;
		return this;
	}

	/**
	 * the target wallet_address
	 *
	 * @return walletAddress
	 **/
	public String getWalletAddress() {
		return walletAddress;
	}

	public void setWalletAddress(String walletAddress) {
		this.walletAddress = walletAddress;
	}

	public OutgoingTransfer appId(String appId) {
		this.appId = appId;
		return this;
	}

	/**
	 * the target app_id
	 *
	 * @return appId
	 **/
	public String getAppId() {
		return appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public OutgoingTransfer title(String title) {
		this.title = title;
		return this;
	}

	/**
	 * will appear in transaction history
	 *
	 * @return title
	 **/
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public OutgoingTransfer description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * will appear in transaction history
	 *
	 * @return description
	 **/
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public OutgoingTransfer memo(String memo) {
		this.memo = memo;
		return this;
	}

	/**
	 * 1-kit-xapp_swel_1234567890ab
	 *
	 * @return memo
	 **/
	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public OutgoingTransfer amount(Integer amount) {
		this.amount = amount;
		return this;
	}

	/**
	 * kin amount
	 *
	 * @return amount
	 **/
	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		OutgoingTransfer outgoingTransferRequest = (OutgoingTransfer) o;
		return Objects.equals(this.walletAddress, outgoingTransferRequest.walletAddress) &&
			Objects.equals(this.appId, outgoingTransferRequest.appId) &&
			Objects.equals(this.title, outgoingTransferRequest.title) &&
			Objects.equals(this.description, outgoingTransferRequest.description) &&
			Objects.equals(this.memo, outgoingTransferRequest.memo) &&
			Objects.equals(this.amount, outgoingTransferRequest.amount);
	}

	@Override
	public int hashCode() {
		return Objects.hash(walletAddress, appId, title, description, memo, amount);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class OutgoingTransfer {\n");

		sb.append("    walletAddress: ").append(toIndentedString(walletAddress)).append("\n");
		sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
		sb.append("    title: ").append(toIndentedString(title)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
		sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
