/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kin.ecosystem.core.network.model;


import com.google.gson.annotations.SerializedName;

/**
 * data on a user
 */
public class UserProfile {
	@SerializedName("stats")
	private UserStats stats = null;

	public UserProfile stats(UserStats stats) {
		this.stats = stats;
		return this;
	}


	/**
	 * Get stats
	 * @return stats
	 **/
	public UserStats getStats() {
		return stats;
	}
	public void setStats(UserStats stats) {
		this.stats = stats;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		UserProfile userProfile = (UserProfile) o;
		return this.stats.equals(userProfile.stats);
	}

	@Override
	public int hashCode() {
		return stats.hashCode();
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class UserProfile {\n");

		sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}