package com.kin.ecosystem.network.model;/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/**
 * token issued by marketplace server
 */
public class AuthToken {

    @SerializedName("token")
    private String token = null;
    @SerializedName("activated")
    private Boolean activated = null;
    @SerializedName("expiration_date")
    private String expirationDate = null;
    @SerializedName("app_id")
    private String appID = null;

    public AuthToken token(String token) {
        this.token = token;
        return this;
    }


    /**
     * Get token
     *
     * @return token
     **/
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public AuthToken activated(Boolean activated) {
        this.activated = activated;
        return this;
    }


    /**
     * Get activated
     *
     * @return activated
     **/
    public Boolean isActivated() {
        return activated;
    }

    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    public AuthToken expirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
        return this;
    }


    /**
     * Get expirationDate
     *
     * @return expirationDate
     **/
    public String getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }

    public String getAppID() {
        return appID;
    }

    public void setAppID(String appID) {
        this.appID = appID;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthToken authToken = (AuthToken) o;
        return this.token.equals(authToken.token) &&
            this.activated.equals(authToken.activated) &&
            this.appID.equals(authToken.appID) &&
            this.expirationDate.equals(authToken.expirationDate);
    }

    @Override
    public int hashCode() {
        return token.hashCode() + activated.hashCode() +
            expirationDate.hashCode() + appID.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AuthToken {\n");

        sb.append("    token: ").append(toIndentedString(token)).append("\n");
        sb.append("    activated: ").append(toIndentedString(activated)).append("\n");
        sb.append("    appID: ").append(toIndentedString(appID)).append("\n");
        sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}



