package com.kin.ecosystem.network.model;/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import com.google.gson.annotations.SerializedName;

/**
 * CouponCodeResult
 */
public class CouponCodeResult extends OrderSpendResult{


    @SerializedName("coupon_code")
    private String couponCode = null;

    public CouponCodeResult type(TypeEnum type) {
        this.type = type;
        return this;
    }

    public CouponCodeResult couponCode(String couponCode) {
        this.couponCode = couponCode;
        return this;
    }

    /**
     * a coupon code - appears in a result object of an Order
     * @return couponCode
     **/
    public String getCode() {
        return couponCode;
    }
    public void setCode(String couponCode) {
        this.couponCode = couponCode;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CouponCodeResult couponCodeResult = (CouponCodeResult) o;
        return super.equals(couponCodeResult) && this.couponCode.equals(couponCodeResult.couponCode);
    }

    @Override
    public int hashCode() {
        return super.hashCode() + couponCode.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CouponCodeResult {\n");

        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}



