package com.kin.ecosystem.network.model;/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/**
 * ExternalOrderRequest
 */
public class ExternalOrderRequest {
    @SerializedName("jwt")
    private String jwt = null;

    public ExternalOrderRequest jwt(String jwt) {
        this.jwt = jwt;
        return this;
    }


    /**
     * string serialized JWTBodySpend
     * @return jwt
     **/
    public String getJwt() {
        return jwt;
    }
    public void setJwt(String jwt) {
        this.jwt = jwt;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExternalOrderRequest externalOrderRequest = (ExternalOrderRequest) o;
        return Objects.equals(this.jwt, externalOrderRequest.jwt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(jwt);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ExternalOrderRequest {\n");

        sb.append("    jwt: ").append(toIndentedString(jwt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}



