/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kin.ecosystem.network.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OfferList
 */
public class OfferList {
@SerializedName("offers")
  private List<Offer> offers = null;
  
  public OfferList offers(List<Offer> offers) {
    this.offers = offers;
    return this;
  }

  public OfferList addOffersItem(Offer offersItem) {
    
    if (this.offers == null) {
      this.offers = new ArrayList<Offer>();
    }
    
    this.offers.add(offersItem);
    return this;
  }
  
  /**
  * Get offers
  * @return offers
  **/
  public List<Offer> getOffers() {
    return offers;
  }
  public void setOffers(List<Offer> offers) {
    this.offers = offers;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferList offerList = (OfferList) o;
    return Objects.equals(this.offers, offerList.offers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offers);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferList {\n");
    
    sb.append("    offers: ").append(toIndentedString(offers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



