package com.kin.ecosystem.network.model;/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/**
 * an open order that hasn&#x27;t been submitted yet
 */
public class OpenOrder {

    @SerializedName("id")
    private String id = null;
    @SerializedName("expiration_date")
    private String expirationDate = null;
    @SerializedName("blockchain_data")
    private BlockchainData blockchainData = null;

    public OpenOrder id(String id) {
        this.id = id;
        return this;
    }


    /**
     * Get id
     *
     * @return id
     **/
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public OpenOrder expirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
        return this;
    }


    /**
     * Get expirationDate
     *
     * @return expirationDate
     **/
    public String getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }

    public OpenOrder blockchainData(BlockchainData blockchainData) {
        this.blockchainData = blockchainData;
        return this;
    }


    /**
     * Get blockchainData
     *
     * @return blockchainData
     **/
    public BlockchainData getBlockchainData() {
        return blockchainData;
    }

    public void setBlockchainData(BlockchainData blockchainData) {
        this.blockchainData = blockchainData;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OpenOrder openOrder = (OpenOrder) o;
        return Objects.equals(this.id, openOrder.id) &&
            Objects.equals(this.expirationDate, openOrder.expirationDate) &&
            Objects.equals(this.blockchainData, openOrder.blockchainData);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, expirationDate, blockchainData);
    }
}


