/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kin.ecosystem.network.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TransactionHistoryList
 */
public class TransactionHistoryList {
@SerializedName("transactions")
  private List<TransactionHistoryItem> transactions = null;
  
  public TransactionHistoryList transactions(List<TransactionHistoryItem> transactions) {
    this.transactions = transactions;
    return this;
  }

  public TransactionHistoryList addTransactionsItem(TransactionHistoryItem transactionsItem) {
    
    if (this.transactions == null) {
      this.transactions = new ArrayList<TransactionHistoryItem>();
    }
    
    this.transactions.add(transactionsItem);
    return this;
  }
  
  /**
  * Get transactions
  * @return transactions
  **/
  public List<TransactionHistoryItem> getTransactions() {
    return transactions;
  }
  public void setTransactions(List<TransactionHistoryItem> transactions) {
    this.transactions = transactions;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionHistoryList transactionHistoryList = (TransactionHistoryList) o;
    return Objects.equals(this.transactions, transactionHistoryList.transactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactions);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionHistoryList {\n");
    
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



